<a href="https://colab.research.google.com/github/ParusSlava/DTA_2026/blob/main/homework/29_05_26_Nazar_pandas_viz_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas + Matplotlib: практикум на 80 завдань

**Рівень:** середній (pandas) + початковий (matplotlib)

---

Цей зошит містить **80 завдань**:
- **50 завдань pandas** — поглиблюємо те, що вивчили, додаємо `loc`/`iloc`, `pivot_table`, складніший `groupby`
- **30 завдань візуалізації** — pandas `.plot()` + основи matplotlib з кольорами, стилями та легендами

## Дані
Працюємо з даними стрімінгового сервісу. Два файли:

**`streaming_subscribers.csv`** (600 рядків) — підписники сервісу:

| Стовпець | Опис |
|---|---|
| `subscriber_id` | Унікальний номер підписника |
| `age` | Вік |
| `gender` | Стать (Ч / Ж) |
| `country` | Країна (Україна, Польща, Німеччина, Чехія, Литва, Іспанія) |
| `plan` | Тариф (Basic / Standard / Premium / Family) |
| `monthly_fee` | Місячна плата (грн) |
| `join_date` | Дата реєстрації |
| `is_active` | Активний абонемент (Так / Ні) |

**`streaming_sessions.csv`** (5000 рядків) — сеанси перегляду:

| Стовпець | Опис |
|---|---|
| `session_id` | Унікальний номер сеансу |
| `subscriber_id` | ID підписника (зв'язок з першою таблицею) |
| `date` | Дата перегляду |
| `genre` | Жанр |
| `device` | Пристрій (Smart TV / Laptop / Mobile / Tablet) |
| `duration_min` | Тривалість перегляду в хвилинах |
| `rating` | Оцінка користувача (1-5) |

## Як працювати
- У кожній комірці є коментар з номером завдання — пишіть код під ним
- Запускайте кожну комірку (Shift + Enter), щоб бачити результат
- Якщо забули синтаксис — користуйтесь шпаргалкою з pandas та новою шпаргалкою matplotlib
- Не бійтесь експериментувати!

---

## Підготовка

Запустіть цю комірку — вона завантажує бібліотеки та дані. Усі завдання використовують змінні `subs` (підписники) та `sess` (сеанси).

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

subs = pd.read_csv("streaming_subscribers.csv")
sess = pd.read_csv("streaming_sessions.csv")

# Перетворюємо дати на справжній формат
subs["join_date"] = pd.to_datetime(subs["join_date"])
sess["date"] = pd.to_datetime(sess["date"])

print("Підписники:", subs.shape)
print("Сеанси:", sess.shape)
subs.head()

Підписники: (600, 8)
Сеанси: (5000, 7)

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active
0,1001,19,Ч,Україна,Premium,329,2023-02-27,Ні
1,1002,40,Ж,Польща,Standard,219,2022-03-05,Так
2,1003,60,Ч,Україна,Basic,149,2023-02-20,Так
3,1004,36,Ч,Чехія,Basic,149,2022-02-22,Так
4,1005,34,Ж,Іспанія,Standard,219,2023-08-27,Так

---

# Частина 1. Pandas (50 завдань)

Розділи:
1. Розминка — повторення (1-8)
2. `loc` та `iloc` — вибірка за позиціями та мітками (9-18)
3. Складніший groupby (19-28)
4. `pivot_table` — зведені таблиці (29-36)
5. Робота з датами + обчислення (37-44)
6. Комбіновані завдання (45-50)

## Розділ 1.1. Розминка (завдання 1-8)

Швидке повторення того, що вже знаємо.

**Завдання 1.** Виведіть перші 10 рядків таблиці `sess`.

In [5]:
# Завдання 1:
subs.head(10)

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active
0,1001,19,Ч,Україна,Premium,329,2023-02-27,Ні
1,1002,40,Ж,Польща,Standard,219,2022-03-05,Так
2,1003,60,Ч,Україна,Basic,149,2023-02-20,Так
3,1004,36,Ч,Чехія,Basic,149,2022-02-22,Так
4,1005,34,Ж,Іспанія,Standard,219,2023-08-27,Так
5,1006,37,Ж,Польща,Standard,219,2024-11-17,Так
6,1007,16,Ж,Україна,Premium,329,2024-07-22,Так
7,1008,49,Ч,Німеччина,Standard,219,2022-11-06,Так
8,1009,47,Ж,Німеччина,Basic,149,2023-09-13,Ні
9,1010,40,Ж,Німеччина,Standard,219,2022-10-03,Ні

In [6]:
sess.head(10)

,session_id,subscriber_id,date,genre,device,duration_min,rating
0,51573,1166,2024-04-11,Анімація,Mobile,72,1
1,50017,1429,2024-06-25,Романтика,Mobile,53,5
2,50861,1404,2024-07-05,Бойовик,Smart TV,49,5
3,54446,1520,2024-07-01,Серіал,Laptop,66,3
4,51561,1052,2024-06-13,Бойовик,Laptop,81,5
5,51938,1078,2024-08-27,Документальний,Mobile,60,4
6,52050,1343,2024-02-26,Бойовик,Tablet,86,3
7,54963,1444,2024-08-04,Серіал,Smart TV,56,4
8,50908,1521,2024-04-02,Драма,Smart TV,68,4
9,51976,1555,2024-04-11,Драма,Mobile,84,5

**Завдання 2.** Скільки всього підписників у даних? А сеансів?

> 💡 Атрибут `shape[0]` або функція `len()`.

In [4]:
# Завдання 2:
sess.shape[0]

5000

In [8]:
len(subs)

600

In [9]:
len(sess)

5000

**Завдання 3.** Виведіть кількість підписників по кожній країні. Відсортуйте за спаданням.

> 💡 `value_counts()` вже сортує за спаданням за замовчуванням.

In [17]:
# Завдання 3:
subs.value_counts('country').sort_values( ascending=False)

country
Україна      256
Німеччина    101
Польща        77
Чехія         68
Іспанія       62
Литва         36
Name: count, dtype: int64

**Завдання 4.** Знайдіть середній вік підписників.

In [22]:
# Завдання 4:
subs['age'].mean().round(0)

np.float64(43.0)

**Завдання 5.** Знайдіть мінімальну та максимальну тривалість сеансу.

In [25]:
# Завдання 5:
print(f'Мінімальна тривалість сеансу: ', sess['duration_min'].min())
print(f'Максимальна тривалість сеансу: ', sess['duration_min'].max())

Мінімальна тривалість сеансу:  5
Максимальна тривалість сеансу:  171

**Завдання 6.** Скільки підписників активні (`is_active == "Так"`)?

In [31]:
# Завдання 6:
subs[subs['is_active'] == 'Так'].shape[0]

447

**Завдання 7.** Виведіть тільки сеанси з жанром `Драма` та оцінкою 5.

> 💡 Дві умови через `&`, кожна в дужках.

In [34]:
# Завдання 7:
sess[(sess['genre'] == 'Драма') & (sess['rating'] == 5)]

,session_id,subscriber_id,date,genre,device,duration_min,rating
9,51976,1555,2024-04-11,Драма,Mobile,84,5
68,51372,1447,2024-06-19,Драма,Tablet,93,5
74,53138,1074,2024-01-05,Драма,Laptop,48,5
94,52201,1124,2024-06-17,Драма,Laptop,34,5
117,53459,1454,2024-05-04,Драма,Mobile,77,5
...,...,...,...,...,...,...,...
4852,52566,1345,2024-03-28,Драма,Laptop,43,5
4855,51811,1579,2024-04-04,Драма,Smart TV,99,5
4902,53655,1551,2024-06-30,Драма,Laptop,48,5
4939,50494,1468,2024-01-30,Драма,Smart TV,36,5
4988,53514,1383,2024-01-23,Драма,Smart TV,69,5

**Завдання 8.** Створіть у таблиці `subs` новий стовпець `annual_fee` = `monthly_fee` × 12.

In [36]:
# Завдання 8:
subs['annual_fee'] = subs['monthly_fee'] * 12

subs

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active,annual_fee
0,1001,19,Ч,Україна,Premium,329,2023-02-27,Ні,3948
1,1002,40,Ж,Польща,Standard,219,2022-03-05,Так,2628
2,1003,60,Ч,Україна,Basic,149,2023-02-20,Так,1788
3,1004,36,Ч,Чехія,Basic,149,2022-02-22,Так,1788
4,1005,34,Ж,Іспанія,Standard,219,2023-08-27,Так,2628
...,...,...,...,...,...,...,...,...,...
595,1596,53,Ж,Україна,Premium,329,2022-04-15,Так,3948
596,1597,30,Ч,Україна,Family,449,2024-03-26,Так,5388
597,1598,38,Ч,Німеччина,Family,449,2024-06-12,Так,5388
598,1599,64,Ж,Чехія,Standard,219,2024-05-03,Ні,2628
599,1600,68,Ч,Польща,Standard,219,2022-07-28,Так,2628

## Розділ 1.2. loc та iloc (завдання 9-18)

`iloc` працює за **числовими позиціями** (як індекси у списку):
- `df.iloc[0]` — перший рядок
- `df.iloc[0:5]` — рядки 0-4
- `df.iloc[0, 2]` — рядок 0, стовпець 2
- `df.iloc[:, 1:3]` — усі рядки, стовпці 1-2

`loc` працює за **мітками** (назвами):
- `df.loc[0]` — рядок з міткою 0
- `df.loc[df["age"] > 30, "country"]` — фільтр + конкретний стовпець
- `df.loc[df["plan"] == "Premium", ["age", "country"]]` — фільтр + кілька стовпців

**Завдання 9.** Виведіть перший рядок таблиці `subs` за допомогою `iloc`.

> 💡 `subs.iloc[0]`.

In [37]:
# Завдання 9:
subs.iloc[0]

subscriber_id                   1001
age                               19
gender                             Ч
country                      Україна
plan                         Premium
monthly_fee                      329
join_date        2023-02-27 00:00:00
is_active                         Ні
annual_fee                      3948
Name: 0, dtype: object

**Завдання 10.** Виведіть рядки з 10 по 15 (включно) таблиці `subs` за допомогою `iloc`.

> 💡 `iloc[10:16]` (правий кінець не включається).

In [38]:
# Завдання 10:
subs.iloc[10:16]

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active,annual_fee
10,1011,16,Ч,Іспанія,Family,449,2023-09-17,Так,5388
11,1012,56,Ч,Україна,Standard,219,2024-12-08,Так,2628
12,1013,25,Ч,Іспанія,Standard,219,2023-01-01,Так,2628
13,1014,17,Ч,Україна,Standard,219,2023-07-21,Так,2628
14,1015,55,Ж,Україна,Standard,219,2022-02-14,Ні,2628
15,1016,20,Ч,Польща,Premium,329,2022-06-09,Ні,3948

**Завдання 11.** Виведіть значення з 5-го рядка, 3-го стовпця таблиці `subs`.

> 💡 `iloc[5, 3]`. Нумерація з нуля!

In [39]:
# Завдання 11:
subs.iloc[5, 3]

'Польща'

**Завдання 12.** Виведіть перші 3 стовпці таблиці `sess` (усі рядки) за допомогою `iloc`.

> 💡 `iloc[:, :3]`.

In [40]:
# Завдання 12:
sess.iloc[:, :3]

      session_id  subscriber_id       date
0          51573           1166 2024-04-11
1          50017           1429 2024-06-25
2          50861           1404 2024-07-05
3          54446           1520 2024-07-01
4          51561           1052 2024-06-13
...          ...            ...        ...
4995       52398           1356 2024-08-19
4996       51013           1208 2024-03-17
4997       54579           1174 2024-05-25
4998       52743           1431 2024-07-23
4999       54629           1237 2024-03-15

[5000 rows x 3 columns]

**Завдання 13.** Виведіть рядки 100-104, тільки стовпці `age` та `country`. Використайте `iloc`.

> 💡 `iloc[100:105, [1, 3]]` — індекси стовпців: age=1, country=3.

In [41]:
# Завдання 13:
subs.iloc[100:105, [1, 3]]

     age    country
100   63     Польща
101   21  Німеччина
102   62     Польща
103   48    Україна
104   54    Україна

**Завдання 14.** За допомогою `loc` виведіть тільки тих підписників, у яких вік більше 50. Поверніть тільки стовпці `country` та `plan`.

> 💡 `subs.loc[subs["age"] > 50, ["country", "plan"]]`.

In [42]:
# Завдання 14:
subs.loc[subs['age'] > 50, ['country', 'plan']]

       country      plan
2      Україна     Basic
11     Україна  Standard
14     Україна  Standard
16   Німеччина  Standard
18      Польща  Standard
..         ...       ...
593    Іспанія     Basic
594    Україна     Basic
595    Україна   Premium
598      Чехія  Standard
599     Польща  Standard

[216 rows x 2 columns]

**Завдання 15.** За допомогою `loc` виведіть стовпець `monthly_fee` тільки для активних підписників (`is_active == "Так"`).

In [46]:
# Завдання 15:
subs.loc[subs['is_active'] == 'Так', ['monthly_fee']]

     monthly_fee
1            219
2            149
3            149
4            219
5            219
..           ...
594          149
595          329
596          449
597          449
599          219

[447 rows x 1 columns]

**Завдання 16.** Знайдіть середній вік підписників з тарифом `Premium`, використовуючи `loc`.

> 💡 `subs.loc[subs["plan"]=="Premium", "age"].mean()`.

In [48]:
# Завдання 16:
subs.loc[subs['plan'] == 'Premium', 'age'].mean().round(0)

np.float64(42.0)

**Завдання 17.** Використовуючи `loc`, ЗМІНІТЬ значення `is_active` на `"Так"` для підписника з `subscriber_id == 1001`.

> 💡 `subs.loc[subs["subscriber_id"]==1001, "is_active"] = "Так"`. Потім перевірте результат.

In [49]:
# Завдання 17:
subs.head(5)

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active,annual_fee
0,1001,19,Ч,Україна,Premium,329,2023-02-27,Ні,3948
1,1002,40,Ж,Польща,Standard,219,2022-03-05,Так,2628
2,1003,60,Ч,Україна,Basic,149,2023-02-20,Так,1788
3,1004,36,Ч,Чехія,Basic,149,2022-02-22,Так,1788
4,1005,34,Ж,Іспанія,Standard,219,2023-08-27,Так,2628

In [51]:
subs.loc[subs['subscriber_id'] == 1001, 'is_active'] = 'Так'
subs.head()

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active,annual_fee
0,1001,19,Ч,Україна,Premium,329,2023-02-27,Так,3948
1,1002,40,Ж,Польща,Standard,219,2022-03-05,Так,2628
2,1003,60,Ч,Україна,Basic,149,2023-02-20,Так,1788
3,1004,36,Ч,Чехія,Basic,149,2022-02-22,Так,1788
4,1005,34,Ж,Іспанія,Standard,219,2023-08-27,Так,2628

**Завдання 18.** Виведіть останні 5 рядків таблиці `subs` за допомогою `iloc` (без `tail`).

> 💡 Від'ємні індекси: `iloc[-5:]`.

In [52]:
# Завдання 18:
subs.iloc[-5:]

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active,annual_fee
595,1596,53,Ж,Україна,Premium,329,2022-04-15,Так,3948
596,1597,30,Ч,Україна,Family,449,2024-03-26,Так,5388
597,1598,38,Ч,Німеччина,Family,449,2024-06-12,Так,5388
598,1599,64,Ж,Чехія,Standard,219,2024-05-03,Ні,2628
599,1600,68,Ч,Польща,Standard,219,2022-07-28,Так,2628

## Розділ 1.3. Складніший groupby (завдання 19-28)

Нові можливості:
- `.agg(["sum", "mean", "count"])` — кілька агрегатів одразу
- `.agg({"col1": "mean", "col2": "sum"})` — різні агрегати на різні стовпці
- `.transform("mean")` — повертає те саме число для кожного рядка групи (зручно для нових стовпців)
- `groupby(["col1", "col2"])` — групування за кількома стовпцями
- `.size()` — кількість рядків у кожній групі

**Завдання 19.** Для кожної країни виведіть кількість підписників та середній вік за один виклик `agg`.

> 💡 `subs.groupby("country").agg({"subscriber_id": "count", "age": "mean"})`.

In [53]:
# Завдання 19:
subs.groupby('country').agg({'subscriber_id': 'count', 'age': 'mean'})

           subscriber_id        age
country
Іспанія               62  43.080645
Литва                 36  40.416667
Німеччина            101  45.099010
Польща                77  42.961039
Україна              256  43.566406
Чехія                 68  40.529412

**Завдання 20.** Для кожного тарифу (`plan`) виведіть мінімальний, середній і максимальний вік підписників.

> 💡 `agg(["min", "mean", "max"])` на стовпці `age`.

In [58]:
# Завдання 20:
subs.groupby('plan').agg({'age': ['min', 'mean', 'max']}).round(0)

         age
         min  mean max
plan
Basic     16  45.0  70
Family    16  42.0  70
Premium   16  42.0  70
Standard  16  43.0  70

**Завдання 21.** Для кожного жанру в таблиці `sess` порахуйте кількість сеансів та середню тривалість.

> 💡 `sess.groupby("genre").agg({"session_id": "count", "duration_min": "mean"})`.

In [59]:
# Завдання 21:
sess.groupby('genre').agg({'session_id': 'count', 'duration_min': 'mean'})

                session_id  duration_min
genre
Анімація               653     53.430322
Бойовик                661     52.856278
Документальний         573     52.657941
Драма                  578     52.861592
Жахи                   631     52.240887
Комедія                629     54.125596
Романтика              644     54.711180
Серіал                 631     53.954041

**Завдання 22.** Для кожного пристрою порахуйте середню оцінку (`rating`) та середню тривалість (`duration_min`).

In [61]:
# Завдання 22:
sess.groupby('device').agg({'rating': 'mean', 'duration_min': 'mean'}).round(2)

          rating  duration_min
device
Laptop      3.98         52.85
Mobile      3.99         52.83
Smart TV    4.05         53.61
Tablet      4.01         55.38

**Завдання 23.** Згрупуйте сеанси за двома стовпцями: `genre` та `device`. Порахуйте середню оцінку.

> 💡 `groupby(["genre", "device"])["rating"].mean()`.

In [64]:
# Завдання 23:
sess.groupby(['genre', 'device'])['rating'].mean().round(2)

genre           device
Анімація        Laptop      3.91
                Mobile      4.07
                Smart TV    4.01
                Tablet      3.88
Бойовик         Laptop      4.08
                Mobile      3.81
                Smart TV    3.91
                Tablet      4.07
Документальний  Laptop      4.03
                Mobile      4.00
                Smart TV    4.12
                Tablet      3.98
Драма           Laptop      3.97
                Mobile      4.11
                Smart TV    4.11
                Tablet      4.20
Жахи            Laptop      3.96
                Mobile      3.99
                Smart TV    4.08
                Tablet      4.14
Комедія         Laptop      3.99
                Mobile      4.02
                Smart TV    4.02
                Tablet      3.97
Романтика       Laptop      4.00
                Mobile      3.92
                Smart TV    4.09
                Tablet      4.09
Серіал          Laptop      3.94
                Mobile      4.05
                Smart TV    4.10
                Tablet      3.72
Name: rating, dtype: float64

**Завдання 24.** Скільки сеансів припадає на кожну пару (`genre`, `device`)? Використайте `.size()`.

In [63]:
# Завдання 24:
sess.groupby(['genre', 'device']).size()

genre           device
Анімація        Laptop      185
                Mobile      166
                Smart TV    227
                Tablet       75
Бойовик         Laptop      193
                Mobile      175
                Smart TV    223
                Tablet       70
Документальний  Laptop      175
                Mobile      136
                Smart TV    214
                Tablet       48
Драма           Laptop      154
                Mobile      158
                Smart TV    207
                Tablet       59
Жахи            Laptop      180
                Mobile      162
                Smart TV    210
                Tablet       79
Комедія         Laptop      184
                Mobile      154
                Smart TV    233
                Tablet       58
Романтика       Laptop      203
                Mobile      166
                Smart TV    217
                Tablet       58
Серіал          Laptop      185
                Mobile      166
                Smart TV    220
                Tablet       60
dtype: int64

**Завдання 25.** Додайте до таблиці `sess` новий стовпець `avg_rating_genre` — середня оцінка по жанру для цього сеансу. Використайте `.transform("mean")`.

> 💡 `sess["avg_rating_genre"] = sess.groupby("genre")["rating"].transform("mean")`.

In [74]:
# Завдання 25:
sess['avg_rating_genre'] = sess.groupby('genre')['rating'].transform('mean').round(2)

sess.head()

,session_id,subscriber_id,date,genre,device,duration_min,rating,avg_rating_genre
0,51573,1166,2024-04-11,Анімація,Mobile,72,1,3.98
1,50017,1429,2024-06-25,Романтика,Mobile,53,5,4.02
2,50861,1404,2024-07-05,Бойовик,Smart TV,49,5,3.95
3,54446,1520,2024-07-01,Серіал,Laptop,66,3,4.00
4,51561,1052,2024-06-13,Бойовик,Laptop,81,5,3.95

**Завдання 26.** Додайте до таблиці `subs` стовпець `avg_age_country` — середній вік підписників у країні цього підписника.

In [73]:
# Завдання 26:
subs['avg_age_country'] = subs.groupby('country')['age'].transform('mean').round(2)
subs.head()

,subscriber_id,age,gender,country,plan,monthly_fee,join_date,is_active,annual_fee,avg_age_countre,avg_age_country
0,1001,19,Ч,Україна,Premium,329,2023-02-27,Так,3948,43.57,43.57
1,1002,40,Ж,Польща,Standard,219,2022-03-05,Так,2628,42.96,42.96
2,1003,60,Ч,Україна,Basic,149,2023-02-20,Так,1788,43.57,43.57
3,1004,36,Ч,Чехія,Basic,149,2022-02-22,Так,1788,40.53,40.53
4,1005,34,Ж,Іспанія,Standard,219,2023-08-27,Так,2628,43.08,43.08

**Завдання 27.** Знайдіть країну з найбільшим середнім віком підписників.

> 💡 `groupby + mean + idxmax()` АБО `sort_values(ascending=False).head(1)`.

In [75]:
# Завдання 27:
subs.groupby('country')['age'].mean().idxmax()

'Німеччина'

**Завдання 28.** Для кожної країни порахуйте, скільки активних і скільки неактивних підписників. Використайте `groupby` за двома стовпцями + `size()`.

> 💡 `subs.groupby(["country", "is_active"]).size()`.

In [76]:
# Завдання 28:
subs.groupby(['country', 'is_active']).size()

country    is_active
Іспанія    Ні            16
           Так           46
Литва      Ні             7
           Так           29
Німеччина  Ні            29
           Так           72
Польща     Ні            21
           Так           56
Україна    Ні            66
           Так          190
Чехія      Ні            13
           Так           55
dtype: int64

## Розділ 1.4. pivot_table — зведені таблиці (завдання 29-36)

`pivot_table` створює таблицю, де:
- `index` — що ставимо у рядки
- `columns` — що ставимо у стовпці
- `values` — що рахуємо
- `aggfunc` — який агрегат (за замовч. `"mean"`)

Приклад:
```python
pd.pivot_table(df, index="country", columns="plan", values="age", aggfunc="mean")
```

**Завдання 29.** Створіть зведену таблицю: рядки — `country`, стовпці — `plan`, значення — кількість підписників.

> 💡 `aggfunc="count"`, як `values` можна взяти `subscriber_id`.

In [77]:
# Завдання 29:
pd.pivot_table(subs, index = 'country', columns = 'plan', values = 'subscriber_id', aggfunc = 'count')

plan       Basic  Family  Premium  Standard
country
Іспанія       18       9       13        22
Литва          5       7       10        14
Німеччина     24      17       19        41
Польща        10       9       23        35
Україна       68      34       60        94
Чехія         13      16       16        23

**Завдання 30.** Зведена таблиця: рядки — `country`, стовпці — `plan`, значення — середній вік.

> 💡 `aggfunc="mean"` (за замовчуванням).

In [80]:
# Завдання 30:
pd.pivot_table(subs, index = 'country', columns = 'plan', values = 'age', aggfunc = 'mean').round(0)

plan       Basic  Family  Premium  Standard
country
Іспанія     43.0    39.0     45.0      44.0
Литва       39.0    43.0     38.0      42.0
Німеччина   47.0    46.0     42.0      45.0
Польща      45.0    40.0     39.0      46.0
Україна     45.0    41.0     45.0      43.0
Чехія       41.0    41.0     38.0      41.0

**Завдання 31.** Зведена таблиця по сеансах: рядки — `genre`, стовпці — `device`, значення — середня оцінка.

In [84]:
# Завдання 31:
pd.pivot_table(sess, index = 'genre', columns = 'device', values = 'rating', aggfunc = 'mean').round(2)

device          Laptop  Mobile  Smart TV  Tablet
genre
Анімація          3.91    4.07      4.01    3.88
Бойовик           4.08    3.81      3.91    4.07
Документальний    4.03    4.00      4.12    3.98
Драма             3.97    4.11      4.11    4.20
Жахи              3.96    3.99      4.08    4.14
Комедія           3.99    4.02      4.02    3.97
Романтика         4.00    3.92      4.09    4.09
Серіал            3.94    4.05      4.10    3.72

**Завдання 32.** Зведена таблиця: рядки — `genre`, стовпці — `device`, значення — сумарна тривалість сеансів.

> 💡 `aggfunc="sum"`.

In [86]:
# Завдання 32:
pd.pivot_table(sess, index = 'genre', columns = 'device', values = 'duration_min', aggfunc = 'sum')

device          Laptop  Mobile  Smart TV  Tablet
genre
Анімація          9358    8700     12457    4375
Бойовик          10023    9625     11471    3819
Документальний    9116    6731     11690    2636
Драма             8050    8391     10806    3307
Жахи              9479    8513     11095    3877
Комедія          10208    8427     12034    3376
Романтика        10659    8610     12685    3280
Серіал           10221    8778     11640    3406

**Завдання 33.** Зведена таблиця: рядки — `country`, стовпці — `gender`, значення — кількість підписників.

In [90]:
# Завдання 33:
pd.pivot_table(subs, index = 'country', columns = 'gender', values = 'subscriber_id', aggfunc = 'count')

gender       Ж    Ч
country
Іспанія     32   30
Литва       22   14
Німеччина   51   50
Польща      40   37
Україна    132  124
Чехія       36   32

**Завдання 34.** Зведена таблиця: рядки — `plan`, стовпці — `is_active`, значення — кількість підписників.

In [91]:
# Завдання 34:
pd.pivot_table(subs, index = 'plan', columns = 'is_active', values = 'subscriber_id', aggfunc = 'count')

is_active  Ні  Так
plan
Basic      35  103
Family     26   66
Premium    41  100
Standard   50  179

**Завдання 35.** Створіть зведену таблицю по сеансах: `genre` у рядках, `device` у стовпцях, кількість сеансів. Заповніть пропуски нулями.

> 💡 Параметр `fill_value=0`.

In [94]:
# Завдання 35:
pd.pivot_table(sess, index = 'genre', columns = 'device', values = 'session_id', fill_value=0).round()

device           Laptop   Mobile  Smart TV   Tablet
genre
Анімація        52449.0  52574.0   52460.0  52591.0
Бойовик         52502.0  52530.0   52393.0  52497.0
Документальний  52682.0  52547.0   52571.0  52731.0
Драма           52716.0  52638.0   52531.0  52599.0
Жахи            52558.0  52343.0   52471.0  52459.0
Комедія         52389.0  52603.0   52383.0  52461.0
Романтика       52514.0  52286.0   52412.0  52494.0
Серіал          52436.0  52485.0   52607.0  52337.0

**Завдання 36.** Зведена таблиця: рядки — `country`, значення — кількість підписників та середній `monthly_fee` одночасно.

> 💡 `values=["subscriber_id", "monthly_fee"]` плюс `aggfunc={"subscriber_id":"count", "monthly_fee":"mean"}`.

In [100]:
# Завдання 36:
pd.pivot_table(subs, index = 'country', values = ['subscriber_id', 'monthly_fee'], aggfunc = {'subscriber_id': 'count', 'monthly_fee': 'mean'}).round(2)

           monthly_fee  subscriber_id
country
Іспанія         255.13             62
Литва           284.56             36
Німеччина       261.77            101
Польща          269.65             77
Україна         256.73            256
Чехія           285.62             68

## Розділ 1.5. Робота з датами + обчислення (завдання 37-44)

Нагадування: дати вже перетворено на datetime у комірці підготовки.
- `.dt.year`, `.dt.month`, `.dt.day` — частини дати
- `.dt.day_name()` — назва дня тижня
- Можна віднімати дати: `df["date1"] - df["date2"]` (отримуємо тривалість)

**Завдання 37.** Додайте до таблиці `sess` стовпець `month` — місяць сеансу.

In [102]:
# Завдання 37:
sess['month'] = sess['date'].dt.month
sess.head()

,session_id,subscriber_id,date,genre,device,duration_min,rating,avg_rating_genre,month
0,51573,1166,2024-04-11,Анімація,Mobile,72,1,3.98,4
1,50017,1429,2024-06-25,Романтика,Mobile,53,5,4.02,6
2,50861,1404,2024-07-05,Бойовик,Smart TV,49,5,3.95,7
3,54446,1520,2024-07-01,Серіал,Laptop,66,3,4.00,7
4,51561,1052,2024-06-13,Бойовик,Laptop,81,5,3.95,6

**Завдання 38.** Додайте до таблиці `sess` стовпець `weekday` — назву дня тижня.

> 💡 `.dt.day_name()`.

In [103]:
# Завдання 38:
sess['weekday'] = sess['date'].dt.day_name()
sess.head()

,session_id,subscriber_id,date,genre,device,duration_min,rating,avg_rating_genre,month,weekday
0,51573,1166,2024-04-11,Анімація,Mobile,72,1,3.98,4,Thursday
1,50017,1429,2024-06-25,Романтика,Mobile,53,5,4.02,6,Tuesday
2,50861,1404,2024-07-05,Бойовик,Smart TV,49,5,3.95,7,Friday
3,54446,1520,2024-07-01,Серіал,Laptop,66,3,4.00,7,Monday
4,51561,1052,2024-06-13,Бойовик,Laptop,81,5,3.95,6,Thursday

**Завдання 39.** Скільки сеансів припадає на кожен місяць? Відсортуйте за номером місяця.

> 💡 `groupby("month")` + `size()` або `count`.

In [ ]:
# Завдання 39:

**Завдання 40.** У який день тижня користувачі переглядають найбільше? Згрупуйте за `weekday`, порахуйте кількість сеансів.

In [ ]:
# Завдання 40:

**Завдання 41.** Скільки сеансів відбулось у червні 2024? Відфільтруйте, потім порахуйте.

> 💡 `sess[sess["date"].dt.month == 6]` (бо всі дані за 2024 рік).

In [ ]:
# Завдання 41:

**Завдання 42.** Додайте до таблиці `subs` стовпець `years_with_us` — скільки років підписник з нами (різниця між 2024-12-31 та `join_date` у роках).

> 💡 `(pd.Timestamp("2024-12-31") - subs["join_date"]).dt.days / 365` — округліть як хочете.

In [ ]:
# Завдання 42:

**Завдання 43.** Скільки нових підписників прийшло у кожному році (за `join_date`)? Згрупуйте за роком.

> 💡 `subs["join_date"].dt.year` + `value_counts`.

In [ ]:
# Завдання 43:

**Завдання 44.** Знайдіть місяць 2024 року, коли було найбільше переглядів. Виведіть номер місяця та кількість сеансів.

In [ ]:
# Завдання 44:

## Розділ 1.6. Комбіновані завдання (завдання 45-50)

Найскладніші — поєднують різні концепції.

**Завдання 45.** Знайдіть топ-5 підписників за СУМАРНОЮ тривалістю переглядів. Виведіть `subscriber_id` та сумарну тривалість.

> 💡 Згрупуйте `sess` за `subscriber_id`, порахуйте суму `duration_min`, відсортуйте, візьміть head(5).

In [ ]:
# Завдання 45:

**Завдання 46.** Для кожного жанру знайдіть відсоток сеансів від загальної кількості сеансів.

> 💡 `value_counts(normalize=True) * 100` АБО `groupby + size`, поділене на `len(sess)`, * 100.

In [ ]:
# Завдання 46:

**Завдання 47.** Знайдіть жанр, який має найвищу середню оцінку (`rating`).

> 💡 `groupby + mean + idxmax`.

In [ ]:
# Завдання 47:

**Завдання 48.** Скільки сеансів у кожній країні? Підказка: треба об'єднати дві таблиці.

> 💡 Використайте `merge`: `sess.merge(subs[["subscriber_id", "country"]], on="subscriber_id")`, потім `groupby("country").size()`.

In [ ]:
# Завдання 48:

**Завдання 49.** Який тариф (`plan`) дає найбільшу СЕРЕДНЮ тривалість сеансу? Об'єднайте таблиці, потім згрупуйте.

> 💡 `sess.merge(subs[["subscriber_id","plan"]], on="subscriber_id")` потім `groupby("plan")["duration_min"].mean()`.

In [ ]:
# Завдання 49:

**Завдання 50.** Для кожної країни знайдіть популярний жанр (з найбільшою кількістю сеансів).

> 💡 Об'єднайте таблиці, згрупуйте за `["country", "genre"]`, порахуйте `size`, потім для кожної країни знайдіть жанр з максимумом. Підказка: можна `.groupby("country").idxmax()`.

In [ ]:
# Завдання 50:

---

# Частина 2. Візуалізація (30 завдань)

Розділи:
1. Швидкі графіки через pandas `.plot()` (51-58)
2. Основні типи matplotlib (59-66)
3. Налаштування графіків — заголовки, осі, кольори (67-74)
4. Легенди, кілька серій, subplots (75-80)

> 💡 **Загальне правило:** після кожного `plt....` коду додавайте `plt.show()` — це показує графік.

## Розділ 2.1. Швидкі графіки через pandas (завдання 51-58)

pandas вміє будувати швидкі графіки прямо з даних — метод `.plot()`. Це найшвидший спосіб подивитись на дані.

Параметри:
- `kind="bar"` — стовпчаста діаграма
- `kind="barh"` — горизонтальна стовпчаста
- `kind="line"` — лінійна (за замовчуванням)
- `kind="hist"` — гістограма
- `kind="pie"` — кругова
- `kind="scatter"` — точкова (треба вказати `x` і `y`)
- `title="..."` — заголовок

**Завдання 51.** Побудуйте стовпчасту діаграму кількості підписників по країнах.

> 💡 `subs["country"].value_counts().plot(kind="bar")` + `plt.show()`.

In [ ]:
# Завдання 51:

**Завдання 52.** Побудуйте кругову діаграму (`pie`) розподілу підписників за тарифами.

> 💡 `value_counts().plot(kind="pie")`.

In [ ]:
# Завдання 52:

**Завдання 53.** Побудуйте гістограму розподілу віку підписників.

> 💡 `subs["age"].plot(kind="hist")`.

In [ ]:
# Завдання 53:

**Завдання 54.** Побудуйте гістограму тривалості сеансів з 20 інтервалами (bins).

> 💡 Параметр `bins=20`.

In [ ]:
# Завдання 54:

**Завдання 55.** Побудуйте лінійну діаграму кількості сеансів по місяцях. Спочатку згрупуйте за місяцем, потім `.plot()`.

> 💡 `sess.groupby("month").size().plot()`.

In [ ]:
# Завдання 55:

**Завдання 56.** Побудуйте горизонтальну стовпчасту діаграму кількості сеансів по жанрах.

> 💡 `kind="barh"`.

In [ ]:
# Завдання 56:

**Завдання 57.** Побудуйте стовпчасту діаграму середньої оцінки (`rating`) по жанрах.

> 💡 `groupby("genre")["rating"].mean().plot(kind="bar")`.

In [ ]:
# Завдання 57:

**Завдання 58.** Побудуйте scatter plot (точкову): по осі X — `duration_min`, по осі Y — `rating` (з таблиці `sess`).

> 💡 `sess.plot(kind="scatter", x="duration_min", y="rating")`.

In [ ]:
# Завдання 58:

## Розділ 2.2. Основи matplotlib (завдання 59-66)

matplotlib дає більше контролю. Базовий синтаксис:

```python
plt.figure(figsize=(8, 5))   # розмір графіка
plt.bar(категорії, значення) # bar / line / scatter / hist
plt.title("Заголовок")
plt.xlabel("Назва X")
plt.ylabel("Назва Y")
plt.show()
```

Функції: `plt.bar()`, `plt.barh()`, `plt.plot()`, `plt.hist()`, `plt.scatter()`, `plt.pie()`.

**Завдання 59.** Створіть стовпчасту діаграму через `plt.bar()`. По осі X — країни, по осі Y — кількість підписників.

> 💡 Спочатку отримайте дані: `counts = subs["country"].value_counts()`. Потім: `plt.bar(counts.index, counts.values)`.

In [ ]:
# Завдання 59:

**Завдання 60.** Створіть лінійну діаграму через `plt.plot()`: динаміка кількості сеансів по місяцях.

> 💡 `monthly = sess.groupby("month").size()` + `plt.plot(monthly.index, monthly.values)`.

In [ ]:
# Завдання 60:

**Завдання 61.** Створіть гістограму віку підписників через `plt.hist()` з 15 інтервалами.

> 💡 `plt.hist(subs["age"], bins=15)`.

In [ ]:
# Завдання 61:

**Завдання 62.** Створіть точкову діаграму через `plt.scatter()`: вік підписників по X, місячна плата по Y.

> 💡 `plt.scatter(subs["age"], subs["monthly_fee"])`.

In [ ]:
# Завдання 62:

**Завдання 63.** Створіть кругову діаграму через `plt.pie()`: розподіл сеансів за пристроями.

> 💡 `counts = sess["device"].value_counts()` + `plt.pie(counts.values, labels=counts.index)`.

In [ ]:
# Завдання 63:

**Завдання 64.** Побудуйте графік з розміром 10x6 дюймів через `plt.figure(figsize=...)`. Можна побудувати будь-який — наприклад, кількість сеансів по жанрах.

In [ ]:
# Завдання 64:

**Завдання 65.** Побудуйте горизонтальну стовпчасту діаграму через `plt.barh()`: кількість сеансів по жанрах.

In [ ]:
# Завдання 65:

**Завдання 66.** Побудуйте дві гістограми на одній фігурі (виклик `plt.hist` двічі підряд перед `plt.show()`): вік активних підписників та вік неактивних. Використайте параметр `alpha=0.5` для прозорості.

> 💡 `plt.hist(...активні..., alpha=0.5)` потім `plt.hist(...неактивні..., alpha=0.5)` потім `plt.show()`.

In [ ]:
# Завдання 66:

## Розділ 2.3. Налаштування графіків (завдання 67-74)

Тепер додаємо красу і інформативність:
- `plt.title("...")` — заголовок
- `plt.xlabel("...")`, `plt.ylabel("...")` — підписи осей
- `color="..."` — колір (`"red"`, `"#02C39A"`, `"teal"` тощо)
- `plt.xticks(rotation=45)` — повернути підписи по X
- `plt.grid(True)` — додати сітку
- `plt.figure(figsize=(w, h))` — розмір

**Завдання 67.** Побудуйте стовпчасту діаграму кількості підписників по країнах. Додайте заголовок "Кількість підписників по країнах", підпис осі X "Країна" та осі Y "Кількість".

In [ ]:
# Завдання 67:

**Завдання 68.** Побудуйте графік середньої тривалості сеансу по жанрах. Усі стовпці зробіть КОЛЬОРОМ `teal`.

> 💡 Параметр `color="teal"` всередині `plt.bar()` або `.plot(kind="bar")`.

In [ ]:
# Завдання 68:

**Завдання 69.** Побудуйте гістограму віку з 20 інтервалами. Колір — `"#02C39A"` (бірюзовий), додайте заголовок.

In [ ]:
# Завдання 69:

**Завдання 70.** Побудуйте діаграму кількості сеансів по місяцях. Підписи на осі X поверніть на 45 градусів.

> 💡 `plt.xticks(rotation=45)`.

In [ ]:
# Завдання 70:

**Завдання 71.** Побудуйте стовпчасту діаграму середнього `monthly_fee` по тарифах. Розмір фігури 8x5. Додайте сітку.

> 💡 `plt.grid(True)`. Сітка для bar-діаграм виглядає краще тільки по осі Y: `plt.grid(axis="y")`.

In [ ]:
# Завдання 71:

**Завдання 72.** Побудуйте лінійну діаграму кількості сеансів по місяцях. Тип лінії: пунктир, колір червоний, маркери у вигляді крапок.

> 💡 У `plt.plot()` параметри: `linestyle="--"`, `color="red"`, `marker="o"`. Або скорочено: `"r--o"`.

In [ ]:
# Завдання 72:

**Завдання 73.** Побудуйте scatter plot: вік (X) vs місячна плата (Y). Колір точок зробіть напівпрозорим (`alpha=0.3`).

In [ ]:
# Завдання 73:

**Завдання 74.** Побудуйте кругову діаграму розподілу підписників за тарифами. Покажіть відсотки на кожному секторі.

> 💡 Параметр `autopct="%1.1f%%"` у `plt.pie()`.

In [ ]:
# Завдання 74:

## Розділ 2.4. Легенди, кілька серій, subplots (завдання 75-80)

Кілька серій на одному графіку:
- Кожна серія має параметр `label="..."`
- Викликаємо `plt.legend()` — показуємо легенду

Кілька графіків поруч (subplots):
```python
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].bar(...)
axes[0].set_title("Перший")
axes[1].plot(...)
axes[1].set_title("Другий")
plt.show()
```

**Завдання 75.** На одному графіку побудуйте дві лінії: кількість сеансів по місяцях для Smart TV та для Mobile. Додайте легенду з підписами.

> 💡 Двічі викличте `plt.plot(...)` з різними даними, кожен з параметром `label="..."`. Потім `plt.legend()`.

In [ ]:
# Завдання 75:

**Завдання 76.** На одному графіку побудуйте дві гістограми віку: окремо для чоловіків і жінок (з прозорістю `alpha=0.5` та різними кольорами). Додайте легенду.

In [ ]:
# Завдання 76:

**Завдання 77.** Побудуйте дві стовпчасті діаграми поруч через `subplots(1, 2)`:
- зліва: кількість підписників по країнах
- справа: кількість підписників по тарифах

Кожній додайте заголовок.

In [ ]:
# Завдання 77:

**Завдання 78.** Побудуйте 2x2 сітку графіків (`subplots(2, 2)`):
- (0,0): гістограма віку
- (0,1): кількість сеансів по жанрах (bar)
- (1,0): розподіл пристроїв (pie)
- (1,1): середня тривалість по жанрах (barh)

Кожному додайте заголовок. Розмір фігури — 12x10.

> 💡 `fig, axes = plt.subplots(2, 2, figsize=(12, 10))`. Доступ: `axes[0, 0]`, `axes[0, 1]`, `axes[1, 0]`, `axes[1, 1]`.

In [ ]:
# Завдання 78:

**Завдання 79.** Побудуйте графік середньої оцінки по жанрах. Стовпці пофарбуйте у РІЗНІ кольори (передайте список кольорів у параметр `color`).

> 💡 `color=["red","blue","green","orange","purple","teal","pink","gray"]` — стільки кольорів, скільки жанрів.

In [ ]:
# Завдання 79:

**Завдання 80.** Зробіть фінальний дашборд: 2x1 сітка (один графік над іншим), розмір 10x10.
- зверху: лінійна діаграма кількості сеансів по місяцях, з заголовком "Динаміка переглядів 2024"
- знизу: горизонтальна стовпчаста діаграма топ-10 жанрів за кількістю сеансів, з заголовком "Топ жанрів"

Після всього — `plt.tight_layout()` (виправляє накладання).

> 💡 `fig, axes = plt.subplots(2, 1, figsize=(10, 10))` + наприкінці `plt.tight_layout()`.

In [ ]:
# Завдання 80:

---

# 🎉 Готово!

Якщо ви виконали всі 80 завдань — вітаємо! Ви відпрацювали:

**Pandas (50 завдань):**
- ✅ `loc` та `iloc` — потужна вибірка за позицією та умовою
- ✅ Складніший `groupby` з `.agg()`, `.transform()`, групування за кількома стовпцями
- ✅ `pivot_table` — зведені таблиці у стилі Excel
- ✅ Робота з датами (`.dt.month`, `.dt.day_name`, різниця дат)
- ✅ Об'єднання таблиць через `merge`

**Matplotlib (30 завдань):**
- ✅ Швидкі графіки через pandas `.plot()`
- ✅ Базові функції matplotlib: `bar`, `plot`, `hist`, `scatter`, `pie`
- ✅ Налаштування: заголовки, осі, кольори, сітка
- ✅ Легенди та кілька серій на одному графіку
- ✅ Subplots — кілька графіків поруч

### Порада
Найкращий спосіб запам'ятати — повернутись через тиждень і спробувати найскладніші завдання знову, не підглядаючи. **Так тримати! 🐼📊**